/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/cli": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List available CLI binary downloads for the running server version.
     * @description Each `url` is a direct download from this server. `available: false` means
     *     the binary was not embedded at build time (dev/local builds).
     */
    get: operations["cli_index_handler"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cli/{platform}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Download the CLI binary for a specific platform directly from this server.
     * @description The binary is embedded at build time and always matches the running server
     *     version. Returns 404 if the server was built without embedded binaries
     *     (dev/local builds).
     *
     *     Supported platforms: `linux-x86_64`, `linux-aarch64`, `macos-aarch64`.
     */
    get: operations["cli_download_handler"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/exec": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit JavaScript code for asynchronous execution.
     * @description Returns immediately with an `execution_id`. Use `GET /api/executions/{id}`
     *     to poll status and `GET /api/executions/{id}/output` to read console output.
     *
     *     Two request encodings are accepted, selected by `Content-Type`:
     *     - `application/json` (or no `Content-Type`): a JSON `ExecRequest` body (the
     *     schema below).
     *     - any other type (e.g. `application/javascript`, `text/plain`): the raw
     *     request body is taken as the script source — i.e. a file upload (`curl
     *     --data-binary @script.js`). Optional `heap`, `session`,
     *     `heap_memory_max_mb`, and `execution_timeout_secs` may be passed as
     *     query-string parameters.
     */
    post: operations["exec_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/executions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all known executions (running and recently completed). */
    get: operations["list_executions_handler"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/executions/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the status and result of an execution. */
    get: operations["get_execution_handler"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/executions/{id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel a running execution. */
    post: operations["cancel_execution_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/executions/{id}/output": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read paginated console output from an execution.
     * @description Supports both line-based (`line_offset` / `line_limit`) and byte-based
     *     (`byte_offset` / `byte_limit`) pagination.  Use `has_more` and
     *     `next_line_offset` / `next_byte_offset` to iterate.
     */
    get: operations["get_execution_output_handler"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Return the running server version. */
    get: operations["version_handler"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Generic error body. */
    ApiError: {
      error: string;
    };
    /** @description Result of a cancel request. */
    CancelResult: {
      error?: string | null;
      ok: boolean;
    };
    /** @description A single entry in the CLI download index. */
    CliAsset: {
      /** @description Whether the binary is embedded in this server build. */
      available: boolean;
      /** @description Platform identifier (e.g. `linux-x86_64`). */
      platform: string;
      /** @description Download URL for this binary via the server itself. */
      url: string;
    };
    /** @description Index of available CLI binary downloads for the running server version. */
    CliIndex: {
      /** @description Available platform binaries. */
      assets: components["schemas"]["CliAsset"][];
      /** @description Server (and CLI) version string, e.g. `"0.1.0"`. */
      version: string;
    };
    /** @description Accepted response containing the new execution's ID. */
    ExecAccepted: {
      /** @description Unique identifier for the queued execution. */
      execution_id: string;
    };
    /** @description Request body for executing JavaScript code. */
    ExecRequest: {
      /** @description JavaScript (or TypeScript) source code to execute. */
      code: string;
      /**
       * Format: int64
       * @description Per-execution timeout in seconds (overrides server default).
       */
      execution_timeout_secs?: number | null;
      /** @description Serialised heap snapshot key to restore before execution. */
      heap?: string | null;
      /** @description Per-execution V8 heap memory cap in megabytes. */
      heap_memory_max_mb?: number | null;
      /** @description Filesystem snapshot handle to mount (label or 64-hex CA id), independent of `heap`. */
      fs?: string | null;
      /** @description Session identifier used for tagging / logging. */
      session?: string | null;
      /** @description Arbitrary key/value tags attached to the resulting heap snapshot. */
      tags?: Record<string, string> | null;
    };
    /** @description Detailed status of a single execution. */
    ExecutionInfo: {
      /** @description ISO-8601 timestamp when execution finished (absent while running). */
      completed_at?: string | null;
      /** @description Error message (present when `status` is `failed`). */
      error?: string | null;
      execution_id: string;
      /** @description Heap snapshot key produced after execution. */
      heap?: string | null;
      /** @description Filesystem snapshot CA id produced after execution (when a mount was attached). */
      fs?: string | null;
      /** @description Final return value serialised to JSON (present when `status` is `completed`). */
      result?: string | null;
      /** @description ISO-8601 timestamp when execution started. */
      started_at: string;
      /** @description Current status: `running`, `completed`, `failed`, `cancelled`, `timed_out`. */
      status: string;
    };
    /** @description List of execution summaries. */
    ExecutionList: {
      executions: unknown[];
    };
    /** @description A page of console output from an execution. */
    ExecutionOutput: {
      /** @description Text content for the requested window. */
      data: string;
      /**
       * Format: int64
       * @description Last byte offset in this page (exclusive).
       */
      end_byte: number;
      /**
       * Format: int64
       * @description Last line number in this page (exclusive).
       */
      end_line: number;
      execution_id: string;
      /** @description Whether more output is available beyond this page. */
      has_more: boolean;
      /**
       * Format: int64
       * @description Byte offset to use for the next page (pass as `byte_offset`).
       */
      next_byte_offset: number;
      /**
       * Format: int64
       * @description Line offset to use for the next page (pass as `line_offset`).
       */
      next_line_offset: number;
      /**
       * Format: int64
       * @description First byte offset in this page.
       */
      start_byte: number;
      /**
       * Format: int64
       * @description First line number in this page (0-indexed).
       */
      start_line: number;
      /** @description Execution status at the time of this query. */
      status: string;
      /**
       * Format: int64
       * @description Total bytes written so far.
       */
      total_bytes: number;
      /**
       * Format: int64
       * @description Total lines written so far.
       */
      total_lines: number;
    };
    /** @description A brief summary of a single execution (used in list responses). */
    ExecutionSummary: {
      completed_at?: string | null;
      execution_id: string;
      started_at: string;
      status: string;
    };
    /** @description Optional pagination query parameters for console output. */
    OutputQuery: {
      /**
       * Format: int64
       * @description Maximum number of bytes to return.
       */
      byte_limit?: number | null;
      /**
       * Format: int64
       * @description Return output starting at this byte offset.
       */
      byte_offset?: number | null;
      /**
       * Format: int64
       * @description Maximum number of lines to return.
       */
      line_limit?: number | null;
      /**
       * Format: int64
       * @description Return output starting at this line number (0-indexed).
       */
      line_offset?: number | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  cli_index_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description CLI download index */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["CliIndex"];
        };
      };
    };
  };
  cli_download_handler: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Target platform (linux-x86_64 | linux-aarch64 | macos-aarch64) */
        platform: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description CLI binary (application/octet-stream) */
      200: {
        headers: Record<string, unknown>;
        content?: never;
      };
      /** @description Unknown platform or binary not embedded */
      404: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  exec_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExecRequest"];
      };
    };
    responses: {
      /** @description Execution queued */
      202: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ExecAccepted"];
        };
      };
      /** @description Malformed request body */
      400: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unsupported Content-Type (e.g. multipart/form-data) */
      415: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Internal error */
      500: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  list_executions_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Execution list */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ExecutionList"];
        };
      };
      /** @description Internal error */
      500: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  get_execution_handler: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Execution ID returned by POST /api/exec */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Execution found */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ExecutionInfo"];
        };
      };
      /** @description Execution not found */
      404: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  cancel_execution_handler: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Execution ID to cancel */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cancel accepted */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["CancelResult"];
        };
      };
      /** @description Cannot cancel (e.g. already finished) */
      400: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["CancelResult"];
        };
      };
    };
  };
  get_execution_output_handler: {
    parameters: {
      query?: {
        /** @description Return output starting at this line number (0-indexed). */
        line_offset?: number | null;
        /** @description Maximum number of lines to return. */
        line_limit?: number | null;
        /** @description Return output starting at this byte offset. */
        byte_offset?: number | null;
        /** @description Maximum number of bytes to return. */
        byte_limit?: number | null;
      };
      header?: never;
      path: {
        /** @description Execution ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Output page */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ExecutionOutput"];
        };
      };
      /** @description Execution not found */
      404: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  version_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server version */
      200: {
        headers: Record<string, unknown>;
        content?: never;
      };
    };
  };
}
